### ISSUE TITLE
Vorschlag: Rhythmus Notation

### ISSUE THREAD

**Issue by LeniVWorld** [morrismuehl/CapoeiraEquilibrioLiederbuch#1]
Hey M.,

**Vorschlag:**
Bei den Rhythmen:

"Michi"-Notation:
Standard-Musik-Notation:

I   II   III   IV   V
4  &  1    2    3

Ich schicke dir gleich ne pdf mit meiner Version davon weil ich mit github noch weniger umgehen kann als erwartet. Grundsätzlich: Dadurch das I und II Achtel sind und alles andere Viertel teilt die Michi-Variante den Takt in 5 Schläge. Das finde ich verwirrend und ich glaube es trägt für alle zum Vorteil bei, wenn wir eine musikalisch und timingmäßig korrekte Variante haben. In meiner pdf außerdem Vorteil: Ich nutze ne Art Parameter-Notation, man kann auch verschiedene Rhythmen eintragen und notieren, welcher Sound wie/wo erzeugt wird. Ggf Nachteil: Man muss sich einmal fünf Minuten nehmen, das verstehen zu wollen. Du siehst ja die pdf und kannst das selbst einschätzen.

**Comment by LeniVWorld** [comment]
Edit: Beide Notationen können ja sehr friedlich koexistieren.

Die Michi Variante lässt sich immer an meine dranschreiben, oder, wegen ihrer unschlagbaren Platzeinsparung einfach als Block obendrüber setzen.

**Comment by morrismuehl** [comment]
Ich finde die Idee super!
Sich an einen (westlichen) Standard anzupassen mag langweilig sein, bietet aber mMn immense Vorteile. 


Mir persönlich wäre wichtig die Notizen über den Wörtern beizubehalten (und ggf. zu erweitern). Das geht mit Zahlen akuell nicht weil ich das Ganze aktuell als "Akkord" angebe (und dann entsprechend vermutet wird dass ich mich auf ein Tonintervall beziehe). Deine PDF baue ich gerne schon einmal als Hilfestellung ein, dadurch haben wir ja schonmal eindeutig festgehalten wie die Michi-Notation zu interpretieren ist. 

In Zukunft dann auch gerne die Transformation zur Standard-Notation!

**Comment by morrismuehl** [comment]
Ich habe derweil herausgefunden wie ich das Hochstellen von Zahlen verhindere!

Unserer Zeichensetzung sind damit nun keine Grenzen mehr gesetzt (außer UTF-8 halt). Da ich mein heutiges Prokrastinationspensum bereits überschritten habe werde ich mich die Tage dran setzen

**Comment by morrismuehl** [comment]
So... Ich habe ja nun deine Tabellen eingebaut. Michi's Wunsch ist es afaik seine Notation zu behalten und alles auf 4/4 zu überführen macht es denke ich nicht zwingend leichter für alle! (Das Nachschlagen funktioniert ja jetzt sowieso da wir es einmal richtig notiert haben)

Ich werde das Issue daher schließen, wenn da Einsprüche bestehen gerne wieder eröffnen
